### PR TITLE
improved: sqlmodel v0.0.7

### PR DESCRIPTION
**Pull request by maresb**
Closes #4 

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Thanks @thewchan! This is ready-to-merge, right?

**Comment by thewchan** [comment]
@maresb I usually don't open a new PR and just modify the one made by the bot

**Comment by maresb** [comment]
Only maintainers can do that.

**Comment by maresb** [comment]
Next time! :wink:

**Comment by thewchan** [comment]
Ah gotcha, you're not a maintainer yet, but you are will be soon enough!

**Pull request merged**
